---
all:
  children:
    vagrants:
      hosts:
        box:
        vagrant:
        tester:
      vars:
        ansible_user: vagrant
        ansible_ssh_private_key_file: .vagrant/machines/default/virtualbox/private_key
  hosts:
    localhost:
      ansible_connection: local
