# This playbook assumes the following about the server you are about to initialize:
# 1) you have access to the private key of the ansible-root in the password safe
---
- hosts: all
  sudo: yes
  gather_facts: yes
  pre_tasks:
    - name: Include variables
      include_vars: "{{ item }}"
      with_available_vars_files:
        - secrets.yml
        - common.yml
        - users.yml
        - server/generic.yml
        - server/{{ inventory_hostname_short }}.yml
      tags:
        - always
  roles:
    - galaxy/colstrom.fast
