---
- hosts: all
  sudo: yes
  pre_tasks:
    - name: Detect Hypervisor (if virtual)
      shell: dmesg --notime | grep -i hypervisor\ detected | cut -d ':' -f2 | tr -d " \t\n\r"
      register: hypervisor
      tags:
        - always
  roles:
    - ubuntu/shared
    - ubuntu/init-for-ansible
