---
- hosts: all
  sudo: yes
  gather_facts: true
  pre_tasks:
    - name: Include variables
      include_vars: "{{ item }}"
      with_available_vars_files:
        - secrets.yml
        - common.yml
        - users.yml
        - server/{{ inventory_hostname_short }}.yml
      tags:
        - always
  roles:
    - galaxy/Stouts.backup