---
- hosts: all
  gather_facts: yes
  become: yes
  roles:
    - oefenweb.locales
    - colstrom.fast
    - mikegleasonjr.firewall
    - dev-sec.ssh-hardening
    - geerlingguy.ntp
    - geerlingguy.clamav
    - oefenweb.sudoers
