---
- hosts: all
  gather_facts: yes
  become: yes
  roles:
    - galaxy/oefenweb.locales
    - galaxy/colstrom.fast
    - galaxy/mikegleasonjr.firewall
    - galaxy/dev-sec.ssh-hardening
    - galaxy/geerlingguy.ntp
    - galaxy/geerlingguy.clamav
    - galaxy/oefenweb.sudoers
