---
- hosts: all
  sudo: yes
  gather_facts: yes
  pre_tasks:
    - name: Include variables
      include_vars: "{{ item }}"
      with_vars_files:
        - secrets.yml
        - common.yml
        - users.yml
        - server/generic.yml
        - env/{{ lookup('env','OPS_ENV') | default('production') }}.yml
      tags:
        - always
  roles:
    - galaxy/colstrom.fast
