#
# WARNING: This playbook is dangerous if you are not prepared for the dist-upgrade!
#
# Use sparingly
#
---
- hosts: all
  roles:
    - ubuntu/shared
  tasks:
    - name: update server
      apt:
        update_cache: yes
    - name: upgrade server
      apt:
        upgrade: dist