#
# Use this task for updating users or their associated ssh keys
#
---
- hosts: all
  sudo: yes
  gather_facts: false
  pre_tasks:
    - name: Include variables
      include_vars: "{{ item }}"
      with_available_vars_files:
        - secrets.yml
        - common.yml
        - users.yml
        - server/{{ inventory_hostname_short }}.yml
      tags:
        - always
  roles:
    - role: config/users
      tags:
        - update-users